# Load ~/.bash_prompt, ~/.exports, ~/.aliases and ~/.functions
for file in ~/dotfiles/shell/.{bash_prompt,exports,aliases,functions}; do
	[ -r "$file" ] && source "$file"
done
unset file

# Load ~/.extra
# ~/.extra can be used for settings you don’t want to commit
[ -r ~/.extra ] && source ~/.extra

# homebrew path (and php for pear scripts) at the beginning
export PATH="$(brew --prefix)/bin:$(brew --prefix php55)/bin:$PATH"

# init rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Prefer US English and use UTF-8
#export LC_ALL="en_US.UTF-8"
#export LANG="en_US"

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh
