
DOTFILES="$HOME/dotfiles"

# Path to your oh-my-zsh installation.
export ZSH="$DOTFILES/zsh/oh-my-zsh"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(bower composer common-aliases colorize docker gem git git-flow jsontools mercurial mvn npm vagrant)

source $ZSH/oh-my-zsh.sh

# User configuration
################################################################################

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

[ -r ~/dotfiles/shell/.common ] && source ~/dotfiles/shell/.common
